export default {
  accountNumber: 'hgkj',
  additionalAddress: 'ghjk',
  address: 'ghjk',
  alternativeName: 'utit',
  authEmail: 'va@gmail.com',
  authFullName: 'Elena',
  authPhone: '89041111111',
  authPosition: 'ghjk',
  bankAdress: 'hgjk',
  bankName: 'hgk',
  city: 'hgjk',
  country: 'Russia',
  currency: 'USD',
  details: 'hgjk',
  name: '980',
  region: 'hgkgh',
  registrationNumber: 'hkg',
  swift: 'ghjk',
  taxId: 'ghjk',
  techEmail: 'va@gmail.com',
  techFullName: 'Elena',
  techPhone: '89041111111',
  zip: 'hk',
};
